### ISSUE TITLE
Image provide fails ungracefully if no persistence is found

### ISSUE THREAD

**Issue by SimonEismann** [DescartesResearch/Pet-Supply-Store#36]
If an image provider is started and no persistence is available it currently fails with the exception below. This is probably due to the recent changes, where a connection throws an exception if it takes too long instead of returning null.
```
tools.descartes.petsupplystore.registryclient.loadbalancers.LoadBalancerTimeoutException: Timout at endpoint: generatedb, with target service: tools.descartes.petsupplystore.persistence
        at tools.descartes.petsupplystore.registryclient.loadbalancers.ServiceLoadBalancer.loadBalanceRESTOperation(ServiceLoadBalancer.java:204)
        at tools.descartes.petsupplystore.registryclient.loadbalancers.ServiceLoadBalancer.loadBalanceRESTOperation(ServiceLoadBalancer.java:177)
        at tools.descartes.petsupplystore.image.setup.SetupController.waitForPersistence(SetupController.java:120)
        at tools.descartes.petsupplystore.image.setup.SetupController.fetchCategories(SetupController.java:172)
        at tools.descartes.petsupplystore.image.setup.SetupController.generateImages(SetupController.java:218)
        at tools.descartes.petsupplystore.image.setup.SetupController.startup(SetupController.java:542)
        at tools.descartes.petsupplystore.image.setup.ImageProviderStartup$1.callback(ImageProviderStartup.java:57)
        at tools.descartes.petsupplystore.registryclient.RegistryClient$1.run(RegistryClient.java:168)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by NSchmittUniWue** [comment]
Should the Image Provider wait for the persistence or fail gracefully?

**Comment by SimonEismann** [comment]
Both seems fine, waiting would be neat but not necessary

**Comment by NSchmittUniWue** [comment]
Image Provider is now waiting for the persistence if a call to generatedb times out.
